version: "2"
services:
  token-mysql:
    image: mysql/mysql-server:5.7
    container_name: token-mysql
    ports:
    - "3307:3306"
    environment:
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_DATABASE=token_transfer_monitor"
    - MYSQL_ROOT_HOST=%
    volumes:
    - ./db-init:/docker-entrypoint-initdb.d
    command: --explicit_defaults_for_timestamp=1
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
    - 8161:8161
    - 61616:61616
    - 61614:61613
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      commad: -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*